# Generated by Django 4.0.4 on 2022-09-05 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='musician',
            name='salary',
            field=models.FloatField(null=True),
        ),
    ]
